version: '3.7'

services:
  php:
    build: .
    ports:
      - 80:80
    volumes: 
      - ./src:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - test-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  test-mysql-data: