version: '3.7'

services:
  php:
    build: .
    ports:
      - 90:80
    volumes: 
      - ./src:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - test-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: stt_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: example
    ports:
      - "9906:3306"

  adminer:
    image: adminer
    ports:
      - 9090:8080

volumes:
  test-mysql-data: